# Generated by Django 5.2.8 on 2025-12-09 07:19

from django.db import migrations
from django.db import migrations
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

sql = (BASE_DIR / "sql" / "seed_concepts.sql").read_text()

class Migration(migrations.Migration):
    dependencies = [
        ('concepts', '0002_auto_20251209_0719'),
    ]

    operations = [migrations.RunSQL(sql)]