# Generated by Django 5.2.8 on 2025-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20251209_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='concepts.tag'),
        ),
    ]
